export default {
  title: 'Gallery',
  data: [
    {
      date: '2018.07.16',
      coverImage: 'gallery/xiaomi-factory.jpg',
      title: '米兔',
      description: '小米2018年香港上市纪念米兔，我拍出一种工业风，觉得挺适合小米的文艺范儿',
      tags: ['工作', '小米', '摄影', '工业风', '米兔'],
      createdTime: '',
      updatedTime: '',
    },
    {
      date: '2019.10.15',
      coverImage: 'gallery/art_2019_01.jpeg',
      title: '艺术照',
      description: '很喜欢这张，眼神和嘴角透露出当时自己的害羞和不知所措，完美的记录了那时候最真实的自己。',
      tags: ['摄影'],
      createdTime: '2021.05.16',
      updatedTime: '',
    },
    {
      date: '2019.10.15',
      coverImage: 'gallery/art_2019_02.jpeg',
      title: '艺术照',
      description: '这张被很多人喜欢，但是我更喜欢上面那张不自在的自己，可能这张相对的“正常”点～',
      tags: ['摄影'],
      createdTime: '2021.05.16',
      updatedTime: '',
    },
    {
      date: '',
      coverImage: 'gallery/kanasi.jpg',
      title: '新疆喀纳斯',
      description: 'iphone 7 随意抓拍，无滤镜，无ps',
      tags: ['摄影', '旅行', '中国', '新疆', '风景'],
      createdTime: '',
      updatedTime: '',
    },
    {
      date: '',
      coverImage: 'gallery/wired-ox.jpg',
      title: '《金角犀牛》',
      description: '“期待寻找一种可以将人暂时抽离出无关紧要的琐碎现实，去感受自然定律的遵守与违背”<br>我对这段话的理解是，现实生活就这样明明白白的摆在每个人面前，我不能改变现实规律，但是我能让自己的思想抽离现实，去大胆的畅想，思想是自由的，不被现实所束缚。例如这头犀牛，现实中它大部分的状态不会出现这样的头身比例，但是我们可以偶尔抽离于现实规律去幻想。',
      tags: [],
      createdTime: '',
      updatedTime: '',
    },
    {
      date: '',
      coverImage: 'gallery/loneliest-tree.jpg',
      title: '最孤独的树',
      description: '',
      tags: ['摄影', '旅行', '国外', '新西兰', '风景', '孤独'],
      createdTime: '',
      updatedTime: '',
    },
  ],
};
