export default {
  title: 'Movie',
  data: [
    {
      date: '2021.05.03',
      coverImage: 'movie/shoufagongmin.webp',
      title: '< Law Abiding Citizen >',
      description: '中文翻译《守法公民》<br>这部电影是和爸爸一起看的，起初是在微博上看到了电影片段，被情节和特效吸引，但是看完了，最值得思考的终究还是人性。<br>电影开始的时候有想换成更加经典的《辛德勒的名单》和爸爸一起看，感觉可以讨论的点更多，思考的更多。但是《守法公民》主人公 Clyde “简简单单”、“老套”、“精彩”的复仇，让 29 岁的我有了新的思考。<br>Clyde 在失去至亲后所做的一切疯狂行为，换做以前的我，我会觉得他报复是因为他失去至亲的痛苦驱使的，但是现在的我会有另一层看法，驱使他做这一切的不是失去至亲的痛苦，而是自责，自责当时自己的无能为力。所以对于我来说全片更像是自我救赎，而不是真正的复仇。<br>可能是因为今年发生了一件突发事件，让我措手不及，让我倍感无力，感到无能为力的自责，让我有了这一层的解读，事发后，总是想着“如果当时我可以。。。”我能做的是，变得更强大，足以处理好类似事件。而 Clyde 再也没有机会了，他所能做的就是杀光当时自己无法杀掉的人...',
      tags: ['电影', '人性'],
      createdTime: '20210505',
      updatedTime: '',
      children: [
        {
          coverImage: 'movie/shoufagongmin-1.webp',
          title: '',
          description: '',
          createdTime: '',
          updatedTime: '',
        },
      ],
    },
    {
      date: '2021.05.03',
      coverImage: 'movie/a_woman_in_berlin.webp',
      title: '< A Woman In Berlin >',
      description: '中文翻译《柏林的女人》<br>又是德国二战题材的电影，通过这部电影我发现自己真的喜欢看这类题材的电影，在残忍的战争中寻找温暖，无论是亲情还是爱情，抑或是友情所展现的温暖。在残忍的战争背景下，这样的温暖难能可贵，可以让人重燃希望之光。<br>这张截图的场景是 Andre 在向 “女记者” 确认是否有藏匿德军战士，这个眼神充满了信任。在平凡生活中，信任很珍贵，更何况在动荡不安的时代，冒着叛国的风险如此相信着一个人...可以说他单纯，但是爱情不就应该是最纯粹的么...',
      tags: ['电影', '战争', '爱情', '女性'],
      createdTime: '20210516',
      updatedTime: '',
      children: [
        {
          coverImage: 'movie/a_woman_in_berlin_01.webp',
          title: '',
          description: '',
          createdTime: '',
          updatedTime: '',
        },
      ],
    },
    {
      date: '2021.05.03',
      coverImage: 'movie/zwartboek.webp',
      title: '< Zwartboek >',
      description: '中文翻译《黑皮书》<br>这部电影我看了2遍，吸引我的不仅仅是动荡时代的爱情，还有坚韧、智慧、勇敢的女主 Rachel。<br>截图的场景是女主被当作卖国贼，被自己的国人侮辱蹂躏，这个片段我是最不愿意看的，因为那些人的嘴脸，让我觉得绝望。但在这样的情形下， Rachel 依旧！她依旧顽强坚韧！值得人无限敬佩！',
      tags: ['电影', '战争', '爱情', '女性'],
      createdTime: '20210516',
      updatedTime: '',
      children: [
        {
          coverImage: 'movie/zwartboek_01.webp',
          title: '',
          description: '',
          createdTime: '',
          updatedTime: '',
        },
      ],
    },
    {
      date: '2020.03.31',
      coverImage: 'movie/qifengle.webp',
      title: '< 起风了 >',
      description: '“我仍感叹于世界之大，也沉醉于儿时情话，不剩真假，不做挣扎，不畏笑话，我终将青春还给了他，连同指尖弹出的盛夏，心之所动就随风去吧” — 《起风了》<br>原来这首歌和宫崎骏的动画有关，虽然这部还没看，但是搜到封面的后，依旧给我熟悉的感触，其实每次看宫崎骏的动画时，往往被里面场景给触动到，一种熟悉而已悲伤的感觉…不知道为什么，虽然场景是那么的和谐美好安逸幸福的感觉，但是我内心中却总是多了一丝悲凉…<br><br>“我仍感叹于世界之大，也沉醉于儿时情话”<br>虽然现在的我心境思想什么的都已经长大了，经历了些事情，但我觉得过去都是美好的，是我人生中的一部分，即使过程中痛苦过，但是还是沉醉于儿时情话，忠于内心～',
      tags: ['电影', '歌词'],
      createdTime: '',
      updatedTime: '',
      children: [
        {
          coverImage: 'movie/qifengle.webp',
          title: '',
          description: '',
          createdTime: '',
          updatedTime: '',
        },
      ],
    },
    {
      date: '2020.03.31',
      coverImage: 'movie/little-women.webp',
      title: '< Little Womem >',
      description: '拥有独立人格，懂得照顾自己，妥帖处理事情，尽情享受生活，自己的苦难自己有能力消释，很少表现出攻击性，因内心强大而生出一种体恤式的温柔，不被廉价的言论与情感煽动，坚持自己的判断不后悔，不在乎别人是否喜欢自己。',
      tags: ['电影', '情感', '女性'],
      createdTime: '',
      updatedTime: '',
      children: [
        {
          coverImage: 'movie/little-women.webp',
          title: '',
          description: '',
          createdTime: '',
          updatedTime: '',
        },
      ],
    },
    {
      date: '2020.03.31',
      coverImage: 'movie/joker.webp',
      title: '< JOKER >',
      description: '“每当你想批评别人的时候，要记住，这世上并不是所有人…都有你拥有的那些优势。”-《了不起的盖茨比》<br>在读《小丑》的影片中看到的这句话，<br>《小丑》这部电影真的是打开了我内心深处的纠结的一面，他替我释放了，也让我看到一种“效果”.<br>这部电影让我看的非常爽！',
      tags: ['电影', '人性'],
      createdTime: '',
      updatedTime: '',
      children: [
        {
          coverImage: 'movie/joker-1.jpg',
          title: '',
          description: '',
          createdTime: '',
          updatedTime: '',
        },
      ],
    },
    {
      date: '2020.03.31',
      coverImage: 'movie/goodWillHunting.webp',
      title: '< Good Will Hunting >',
      description: '中文翻译《心灵捕手》<br>很喜欢电影最后的这个场景，无论是从“角色”、构图、色彩都能表达好多情绪，而这些情绪很让我舒服。“角色”和构图不谈了，对于我来说就是老套的自由。而色调我觉得很棒，奔向自由并不是用鲜亮的阳光色去展示，而是用这个类似老电影色调，看似有点悲凉浑浊的色彩，仿佛告诉我，目的地有可能不是那么一片光明，但是我还是决定去闯一闯的感觉！但是看到头顶上那一抹鲜黄色的阳光时，仿佛预示着你的目标是对的，继续下去吧…不过我还是喜欢我对他的第一眼解释。<br>“前方一定不平稳，但是我愿意为之闯一闯”',
      tags: ['电影', '人性'],
      createdTime: '',
      updatedTime: '',
      children: [
        {
          coverImage: 'movie/goodWillHunting-1.jpeg',
          title: '',
          description: '',
          createdTime: '',
          updatedTime: '',
        },
      ],
    },
    {
      date: '2020.03.31',
      coverImage: 'movie/langduzhe.webp',
      title: '< The Reader >',
      description: '',
      tags: ['电影', '人性', '爱情'],
      createdTime: '20210505',
      updatedTime: '',
      children: [
        {
          coverImage: 'movie/langduzhe.webp',
          title: '',
          description: '中文翻译《朗读者》<br>在看完《辛德勒的名单》后，被 Ralph Fiennes 眼神折服，所以开启了这部我曾经刷到却提不起兴趣的电影《朗读者》。',
          createdTime: '',
          updatedTime: '',
        },
        {
          coverImage: 'movie/langduzhe-1.webp',
          title: '',
          description: '这个场景是，Hanna 和 年轻的 Michael 正式约会出去玩，由于外在年龄表象，被当地人误认为是母子，这时，年轻的 Michael 就当众给 Hanna 一个 kiss，以证明他们恋人的关系，是证明，更是爱情的真挚与浓烈，无所谓他人的眼光及评判。也为后面 Hanan 不辞而别，年轻的 Michael 伤心欲绝做了铺垫。',
          createdTime: '',
          updatedTime: '',
        },
        {
          coverImage: 'movie/langduzhe-2.webp',
          title: '',
          description: '这个场景是 Hanna 被判刑，年轻的 Michael 没有站出来为她证明她不识字的有力证据，一开始我会认为，是他不想，后来发现，其实是她不想，而他是尊重她的。',
          createdTime: '',
          updatedTime: '',
        },
        {
          coverImage: 'movie/langduzhe-3.webp',
          title: '',
          description: '成熟后的 Michael 来了，从他眼神中透漏出更加坚定的性格，是经历过悲伤后的坚定。',
          createdTime: '',
          updatedTime: '',
        },
      ],
    },
    {
      date: '2020.03.31',
      coverImage: 'movie/schindlersList.webp',
      title: "< Schindler's List >",
      description: '经典电影《辛德勒的名单》<br>喜欢里面的德国纳粹狂热分子 Amon.因为他在剧中的人物形象对于我来说鲜明又复杂，相对于 Schindler 一个一开始就“不坏”的普通商人，从光明走向更光明的形象，而 Amon 在我看来他是挣扎在光明与黑暗之中。<br>从 Schindler “教导”他学会宽恕“ i forgive you”，他真的尝试着去宽恕一个两个 Jew，但是后来他还是抵抗不了内心的顽固的印记…<br>再是他对 Helen 的爱意，我和喜欢这两个表情中的眼神，透露着故事，这是当 Helen 帮他修指甲的时候，他看着 Helen，这些都足以表达他对 Helen 的复杂的情感，复杂也是相对于 Amon 本身，他疑惑、肯定、质疑、崩溃…他从糜烂的派对上跑到 Helen 的房间时，那时的他肯定自己对 Helen 的感情，但是当他想认真面对思考这份感情时，他摇摆，最终还是战胜不了内心的那道印记，只能通过暴力去隐藏自己可悲的爱情…<br>其实这些文字，不仅可以通过我的理解去认识 Amon，真实的是从中看出那个我自己，因为我目前就是这个状态吧，没有完全认识自己的状态…记录这篇，仅以让未来的自己看看当时26岁的我是什么样的思想…',
      tags: ['电影', '人性'],
      createdTime: '',
      updatedTime: '',
      children: [
        {
          coverImage: 'movie/schindlersList-1.jpeg',
          title: '',
          description: '',
          createdTime: '',
          updatedTime: '',
        },
        {
          coverImage: 'movie/schindlersList-2.jpeg',
          title: '',
          description: '',
          createdTime: '',
          updatedTime: '',
        },
      ],
    },
    {
      date: '2019.8.26',
      coverImage: 'movie/theGreatGatsby.jpeg',
      title: '< The Great Gatsby >',
      description: '中文翻译《了不起的盖兹比》<br>我花了两天时间分段式60%+40%的方式看完了整部电影。<br>其实我很早就这道这部电影了，但是首先由于他的片名，让我联想到比尔盖茨，我觉得这是一部商业主题电影所以不感兴趣…第二次又刷到这部电影，看了它的海报给我一种科幻赌博的电影瞬间又了点兴趣，但是由于小李子一些负面油腻新闻，我不想看…<br>开头就像豆瓣里说的纸醉金迷的感觉，我觉得这个太drama，夸张了，而且还是以这种方式追前女友…omg，感觉比国产网剧还要狗血…虽然影片拍摄质感和演员演技都值得一赞，但是前60%的剧情………所以剩余的40%我就留到了第二天才看。<br>不过发现我的生活倒也蛮戏剧性的，就恰恰停在了60%的位置，因为剩余的40%真的彻彻底底的让我对这部电影180%大反转！特别是最后结尾部分，一个是盖兹比中枪后那复杂的眼神和口中的 Daisy，这个场景让我真的心情跌宕起伏也超级复杂，站在盖兹比的角度他高兴又难过，因为他认为是daisy的电话愿意跟他远走高飞，但是我却…又要再次失去跟她在一起的机会了…<br>但是站在我的角度起初和盖兹比一样的心情，但是直到电影画面切到原来是 Nick 打得来的电话，这个现实这个结果其实对于将死的盖兹比来说是比死更难以接受的事实，所以我觉得他可以中弹，因为直到死去前他都是对爱情对人性对生活都是充满着积极乐观的态度，就像 Nick 对他的描述，他的内心纯洁无比…在片尾 Nick feel disgusting about the golden world，所以他对于盖兹比的评价更高了，没人比得上他，He is great!',
      tags: ['电影', '人性'],
      createdTime: '',
      updatedTime: '',
      children: [
        {
          coverImage: 'movie/theGreatGatsby-1.jpeg',
          title: '',
          description: '',
          createdTime: '',
          updatedTime: '',
        },
        {
          coverImage: 'movie/theGreatGatsby-2.jpeg',
          title: '',
          description: '',
          createdTime: '',
          updatedTime: '',
        },
      ],
    },
  ],
};
