export default {
  title: 'Read',
  data: [
    {
      date: '2020',
      coverImage: 'read/图解西方现代艺术史.jpeg',
      title: '《图解西方现代艺术史》',
      description: '',
      tags: [],
      createdTime: '',
      updatedTime: '',
      children: [],
    },
    {
      date: '2021.03.02',
      coverImage: 'read/大地的窗口.jpeg',
      title: '《大地的窗口》',
      description: '',
      tags: [],
      createdTime: '',
      updatedTime: '',
      children: [],
    },
    {
      date: '2020',
      coverImage: 'read/如果.jpeg',
      title: '《如果没有今天，明天会不会有昨天？》',
      description: '',
      tags: [],
      createdTime: '',
      updatedTime: '',
      children: [],
    },
    {
      date: '2020.03.31',
      coverImage: 'read/geniusAndCrazy.jpg',
      title: '天才在左，疯子在右',
      description: '',
      tags: ['人类', '世界', '对错是非'],
      createdTime: '',
      updatedTime: '',
      children: [],
    },
    {
      date: '2019',
      coverImage: 'read/忒修斯之船.jpeg',
      title: '《忒修斯之船》',
      description: '',
      tags: [],
      createdTime: '',
      updatedTime: '',
      children: [],
    },
    {
      date: '2021.03.02',
      coverImage: 'read/时间的秩序.jpeg',
      title: '《时间的秩序》',
      description: '',
      tags: [],
      createdTime: '',
      updatedTime: '',
      children: [],
    },
    {
      date: '2019',
      coverImage: 'read/沉思录.jpeg',
      title: '《沉思录》',
      description: '',
      tags: [],
      createdTime: '',
      updatedTime: '',
      children: [],
    },
    {
      date: '2019',
      coverImage: 'read/月亮与六便士.jpeg',
      title: '《月亮与六便士》',
      description: '',
      tags: [],
      createdTime: '',
      updatedTime: '',
      children: [],
    },
    {
      date: '2019',
      coverImage: 'read/prideAndPrejudice.jpeg',
      title: '《Pride And Prejudice》',
      description: '',
      tags: [],
      createdTime: '',
      updatedTime: '',
      children: [],
    },
    {
      date: '2019',
      coverImage: 'read/toKillAMockingbird.jpeg',
      title: '《To Kill A Mockingbird》',
      description: '',
      tags: [],
      createdTime: '',
      updatedTime: '',
      children: [],
    },
    {
      date: '2019',
      coverImage: 'read/呐喊.jpeg',
      title: '《呐喊》',
      description: '',
      tags: [],
      createdTime: '',
      updatedTime: '',
      children: [],
    },
    {
      date: '2019',
      coverImage: 'read/狂人日记.jpeg',
      title: '《狂人日记》',
      description: '',
      tags: [],
      createdTime: '',
      updatedTime: '',
      children: [],
    },
    {
      date: '2020.03.31',
      coverImage: 'read/撒哈拉的故事.jpg',
      title: '撒哈拉的故事',
      description: '',
      tags: ['爱情', '文艺', '女性'],
      createdTime: '',
      updatedTime: '',
      children: [
        {
          coverImage: 'read/撒哈拉的故事-1.jpg',
          title: '三毛和河西',
          description: '',
          createdTime: '',
          updatedTime: '',
        },
        {
          coverImage: 'read/撒哈拉的故事-2.jpg',
          title: '三毛',
          description: '向往',
          createdTime: '',
          updatedTime: '',
        },
      ],
    },
    {
      date: '2019',
      coverImage: 'read/梦里花落知多少.jpeg',
      title: '《梦里花落知多少》',
      description: '',
      tags: [],
      createdTime: '',
      updatedTime: '',
      children: [],
    },
    {
      date: '2015',
      coverImage: 'read/相逢.jpeg',
      title: '《相逢》',
      description: '',
      tags: [],
      createdTime: '',
      updatedTime: '',
      children: [],
    },
  ],
};
